export interface Manufacturer {
  id: string
  name: string
  slug: string
  location: string
  country: string
  description: string
  logo?: string
}

export interface HouseModel {
  id: string
  name: string
  slug: string
  manufacturerId: string
  size_sqm: number
  bedrooms: number
  bathrooms: number
  price_range: string
  category: string
  style_tags: string[]
  features: string[]
  images: string[]
  description: string
}

// Mock data: 6 Latvian prefab home manufacturers
export const manufacturers: Manufacturer[] = [
  {
    id: "1",
    name: "Nordic Prefab Latvia",
    slug: "nordic-prefab-latvia",
    location: "Riga, Latvia",
    country: "Latvia",
    description: "Leading manufacturer of Scandinavian-inspired prefab homes with sustainable materials and energy-efficient designs.",
    logo: "/placeholder-logo.svg",
  },
  {
    id: "2",
    name: "Baltic Modular Homes",
    slug: "baltic-modular-homes",
    location: "Liepāja, Latvia",
    country: "Latvia",
    description: "Specializing in modern modular homes and tiny houses, combining Baltic design aesthetics with contemporary living.",
    logo: "/placeholder-logo.svg",
  },
  {
    id: "3",
    name: "EcoHaus Latvia",
    slug: "ecohaus-latvia",
    location: "Jūrmala, Latvia",
    country: "Latvia",
    description: "Eco-friendly prefab homes focusing on passive house standards and renewable energy integration.",
    logo: "/placeholder-logo.svg",
  },
  {
    id: "4",
    name: "Latvian Timber Homes",
    slug: "latvian-timber-homes",
    location: "Valmiera, Latvia",
    country: "Latvia",
    description: "Traditional and modern timber-frame prefab homes using locally sourced Latvian wood.",
    logo: "/placeholder-logo.svg",
  },
  {
    id: "5",
    name: "Scandinavian Prefab Co.",
    slug: "scandinavian-prefab-co",
    location: "Cēsis, Latvia",
    country: "Latvia",
    description: "Premium prefab homes inspired by Scandinavian design, offering customizable floor plans and finishes.",
    logo: "/placeholder-logo.svg",
  },
  {
    id: "6",
    name: "GreenBox Homes Latvia",
    slug: "greenbox-homes-latvia",
    location: "Daugavpils, Latvia",
    country: "Latvia",
    description: "Innovative container-based and modular prefab homes with modern amenities and sustainable construction.",
    logo: "/placeholder-logo.svg",
  },
]

// House models for each manufacturer
export const houseModels: HouseModel[] = [
  // Nordic Prefab Latvia models
  {
    id: "m1",
    name: "Nordic Compact",
    slug: "nordic-compact",
    manufacturerId: "1",
    size_sqm: 45,
    bedrooms: 1,
    bathrooms: 1,
    price_range: "€45,000 - €55,000",
    category: "Tiny House",
    style_tags: ["Scandinavian", "Minimalist", "Modern"],
    features: ["Energy-efficient insulation", "Triple-glazed windows", "Solar-ready", "Loft sleeping area"],
    images: [
      "https://i.pinimg.com/736x/c5/e4/55/c5e4552dd82a23fc40e19c28292b41d3.jpg",
      "https://i.pinimg.com/1200x/3b/13/20/3b13204e4f7e4b6ccdc81668a14dcee2.jpg",
    ],
    description: "A compact Scandinavian-inspired tiny home perfect for minimalists. Features clean lines, natural wood finishes, and energy-efficient design principles.",
  },
  {
    id: "m2",
    name: "Nordic Family",
    slug: "nordic-family",
    manufacturerId: "1",
    size_sqm: 85,
    bedrooms: 3,
    bathrooms: 2,
    price_range: "€85,000 - €105,000",
    category: "Modular",
    style_tags: ["Scandinavian", "Modern", "Family-friendly"],
    features: ["Open-plan living", "Large windows", "Underfloor heating", "Sustainable materials", "Customizable layout"],
    images: [
      "https://i.pinimg.com/1200x/60/6e/82/606e82826f3b2d29542b7bc6d8808124.jpg",
      "https://i.pinimg.com/1200x/74/f0/eb/74f0ebdf27048502ff1481ac55fb5b11.jpg",
    ],
    description: "Spacious modular home designed for families, combining Nordic aesthetics with practical living spaces. Features multiple bedrooms and modern amenities.",
  },
  {
    id: "m3",
    name: "Nordic A-Frame",
    slug: "nordic-a-frame",
    manufacturerId: "1",
    size_sqm: 60,
    bedrooms: 2,
    bathrooms: 1,
    price_range: "€65,000 - €80,000",
    category: "A-Frame",
    style_tags: ["Scandinavian", "Rustic", "Modern"],
    features: ["Iconic A-frame design", "High ceilings", "Wood-burning stove", "Large deck", "Mountain-ready"],
    images: [
      "https://i.pinimg.com/1200x/0a/7a/b3/0a7ab3959ca4eafc0bb5b3894e436a62.jpg",
      "https://i.pinimg.com/1200x/11/d2/10/11d210e05a5b32398d2ccbe532abef4a.jpg",
    ],
    description: "Classic A-frame cabin with Nordic design touches. Perfect for weekend getaways or year-round living in scenic locations.",
  },
  // Baltic Modular Homes models
  {
    id: "m4",
    name: "Baltic Tiny",
    slug: "baltic-tiny",
    manufacturerId: "2",
    size_sqm: 28,
    bedrooms: 1,
    bathrooms: 1,
    price_range: "€35,000 - €42,000",
    category: "Tiny House",
    style_tags: ["Modern", "Minimalist", "Baltic"],
    features: ["Space-efficient design", "Multi-functional furniture", "Compact kitchen", "Loft bedroom", "Portable"],
    images: [
      "https://i.pinimg.com/736x/74/7a/f0/747af0643f80bc35f7cb45d52dcfb575.jpg",
      "https://i.pinimg.com/736x/c5/a9/39/c5a9397941a16c90c830e8a57350ceca.jpg",
    ],
    description: "Ultra-compact tiny home with Baltic design influences. Maximizes every square meter with innovative storage solutions and modern finishes.",
  },
  {
    id: "m5",
    name: "Baltic Modular 2",
    slug: "baltic-modular-2",
    manufacturerId: "2",
    size_sqm: 75,
    bedrooms: 2,
    bathrooms: 2,
    price_range: "€75,000 - €90,000",
    category: "Modular",
    style_tags: ["Modern", "Contemporary", "Baltic"],
    features: ["Modular construction", "Quick assembly", "Customizable modules", "Energy-efficient", "Expandable"],
    images: [
      "https://i.pinimg.com/736x/e6/e3/46/e6e3468c1f64983f502d9f448de2d8bc.jpg",
      "https://i.pinimg.com/736x/b1/bc/61/b1bc61af6e5e04b6698440e8a69fc964.jpg",
    ],
    description: "Flexible modular home system that can be expanded over time. Modern Baltic design with contemporary living spaces and efficient layouts.",
  },
  {
    id: "m6",
    name: "Baltic Studio",
    slug: "baltic-studio",
    manufacturerId: "2",
    size_sqm: 40,
    bedrooms: 1,
    bathrooms: 1,
    price_range: "€42,000 - €52,000",
    category: "Tiny House",
    style_tags: ["Modern", "Minimalist", "Studio"],
    features: ["Open-plan studio", "High ceilings", "Large windows", "Modern appliances", "Urban-friendly"],
    images: [
      "https://i.pinimg.com/1200x/43/25/34/432534d284c5c02f45a13049f17c11e5.jpg",
      "https://i.pinimg.com/1200x/79/94/df/7994df513ac293554df1356be1bfa8ee.jpg",
    ],
    description: "Contemporary studio tiny home perfect for urban settings or as a guest house. Features modern design and efficient use of space.",
  },
  // EcoHaus Latvia models
  {
    id: "m7",
    name: "EcoHaus Passive",
    slug: "ecohaus-passive",
    manufacturerId: "3",
    size_sqm: 70,
    bedrooms: 2,
    bathrooms: 1,
    price_range: "€95,000 - €115,000",
    category: "Modular",
    style_tags: ["Eco-friendly", "Modern", "Sustainable"],
    features: ["Passive house certified", "Solar panels included", "Heat recovery ventilation", "Triple-glazed windows", "Zero-emission"],
    images: [
      "https://i.pinimg.com/1200x/ab/81/2a/ab812a9afae4bd42678eea3d82546951.jpg",
      "https://i.pinimg.com/1200x/83/d7/bc/83d7bcd3f75cc1a24f690bef9cdb642e.jpg",
    ],
    description: "Certified passive house with exceptional energy efficiency. Includes integrated renewable energy systems and sustainable building materials.",
  },
  {
    id: "m8",
    name: "EcoHaus Tiny",
    slug: "ecohaus-tiny",
    manufacturerId: "3",
    size_sqm: 32,
    bedrooms: 1,
    bathrooms: 1,
    price_range: "€48,000 - €58,000",
    category: "Tiny House",
    style_tags: ["Eco-friendly", "Minimalist", "Off-grid"],
    features: ["Off-grid capable", "Composting toilet", "Rainwater collection", "Solar power", "Sustainable materials"],
    images: [
      "https://i.pinimg.com/1200x/e7/b9/51/e7b9514255e66799c7860c073a78dcf8.jpg",
      "https://i.pinimg.com/1200x/a1/cd/b1/a1cdb152fbeabc4c202e74d541140256.jpg",
    ],
    description: "Eco-friendly tiny home designed for off-grid living. Features sustainable systems and minimal environmental impact.",
  },
  {
    id: "m9",
    name: "EcoHaus Family",
    slug: "ecohaus-family",
    manufacturerId: "3",
    size_sqm: 95,
    bedrooms: 3,
    bathrooms: 2,
    price_range: "€125,000 - €145,000",
    category: "Modular",
    style_tags: ["Eco-friendly", "Modern", "Family-friendly"],
    features: ["Passive house standard", "Geothermal heating", "Solar panels", "Green roof option", "Sustainable materials"],
    images: [
      "https://i.pinimg.com/1200x/63/4c/56/634c56c149a614f4261ea3e9f39ea652.jpg",
      "https://i.pinimg.com/1200x/ec/8f/de/ec8fdee37f6dbfa0c7591a12e07f7088.jpg",
    ],
    description: "Large family home built to passive house standards. Combines eco-friendly technology with comfortable family living spaces.",
  },
  // Latvian Timber Homes models
  {
    id: "m10",
    name: "Timber Classic",
    slug: "timber-classic",
    manufacturerId: "4",
    size_sqm: 55,
    bedrooms: 2,
    bathrooms: 1,
    price_range: "€55,000 - €68,000",
    category: "Cabin",
    style_tags: ["Rustic", "Traditional", "Timber"],
    features: ["Locally sourced timber", "Traditional joinery", "Wood-burning stove", "Natural finishes", "Heritage design"],
    images: [
      "https://i.pinimg.com/1200x/fa/fc/65/fafc65673bd6ce8e1c54d8a4fa04f4ab.jpg",
      "https://i.pinimg.com/736x/52/f1/aa/52f1aa3ec27be7dff1e5c2d2fc028436.jpg",
    ],
    description: "Traditional timber-frame cabin using locally sourced Latvian wood. Combines heritage craftsmanship with modern comfort.",
  },
  {
    id: "m11",
    name: "Timber Modern",
    slug: "timber-modern",
    manufacturerId: "4",
    size_sqm: 80,
    bedrooms: 3,
    bathrooms: 2,
    price_range: "€88,000 - €105,000",
    category: "Modular",
    style_tags: ["Modern", "Timber", "Contemporary"],
    features: ["Modern timber construction", "Large windows", "Open-plan design", "Underfloor heating", "Customizable"],
    images: [
      "https://i.pinimg.com/736x/c5/e4/55/c5e4552dd82a23fc40e19c28292b41d3.jpg",
      "https://i.pinimg.com/1200x/3b/13/20/3b13204e4f7e4b6ccdc81668a14dcee2.jpg",
    ],
    description: "Contemporary timber home with modern design elements. Features large windows and open living spaces while maintaining natural wood aesthetics.",
  },
  {
    id: "m12",
    name: "Timber Lodge",
    slug: "timber-lodge",
    manufacturerId: "4",
    size_sqm: 65,
    bedrooms: 2,
    bathrooms: 1,
    price_range: "€68,000 - €82,000",
    category: "Cabin",
    style_tags: ["Rustic", "Lodge", "Timber"],
    features: ["Lodge-style design", "Stone fireplace", "Large deck", "Natural wood interior", "Mountain aesthetic"],
    images: [
      "https://i.pinimg.com/736x/1c/90/0f/1c900fde427244db7fe3632e709b0aeb.jpg",
      "https://i.pinimg.com/1200x/60/6e/82/606e82826f3b2d29542b7bc6d8808124.jpg",
    ],
    description: "Rustic timber lodge perfect for countryside living. Features traditional lodge aesthetics with modern amenities.",
  },
  // Scandinavian Prefab Co. models
  {
    id: "m13",
    name: "Scandi Minimal",
    slug: "scandi-minimal",
    manufacturerId: "5",
    size_sqm: 50,
    bedrooms: 1,
    bathrooms: 1,
    price_range: "€58,000 - €72,000",
    category: "Tiny House",
    style_tags: ["Scandinavian", "Minimalist", "Modern"],
    features: ["Minimalist design", "Premium finishes", "Customizable colors", "High-quality materials", "Designer fixtures"],
    images: [
      "https://i.pinimg.com/1200x/74/f0/eb/74f0ebdf27048502ff1481ac55fb5b11.jpg",
      "https://i.pinimg.com/1200x/0a/7a/b3/0a7ab3959ca4eafc0bb5b3894e436a62.jpg",
    ],
    description: "Premium minimalist tiny home with Scandinavian design principles. Features high-end finishes and customizable options.",
  },
  {
    id: "m14",
    name: "Scandi Family",
    slug: "scandi-family",
    manufacturerId: "5",
    size_sqm: 100,
    bedrooms: 4,
    bathrooms: 2,
    price_range: "€135,000 - €165,000",
    category: "Modular",
    style_tags: ["Scandinavian", "Modern", "Family-friendly"],
    features: ["Premium modular system", "Customizable floor plans", "High-end finishes", "Large windows", "Designer kitchen"],
    images: [
      "https://i.pinimg.com/1200x/11/d2/10/11d210e05a5b32398d2ccbe532abef4a.jpg",
      "https://i.pinimg.com/736x/74/7a/f0/747af0643f80bc35f7cb45d52dcfb575.jpg",
    ],
    description: "Premium Scandinavian family home with customizable layouts. Features high-end materials and designer finishes throughout.",
  },
  {
    id: "m15",
    name: "Scandi Studio",
    slug: "scandi-studio",
    manufacturerId: "5",
    size_sqm: 38,
    bedrooms: 1,
    bathrooms: 1,
    price_range: "€52,000 - €65,000",
    category: "Tiny House",
    style_tags: ["Scandinavian", "Minimalist", "Studio"],
    features: ["Open studio layout", "Premium appliances", "Designer lighting", "Custom storage", "Urban design"],
    images: [
      "https://i.pinimg.com/736x/c5/a9/39/c5a9397941a16c90c830e8a57350ceca.jpg",
      "https://i.pinimg.com/736x/e6/e3/46/e6e3468c1f64983f502d9f448de2d8bc.jpg",
    ],
    description: "Elegant Scandinavian studio home with premium finishes. Perfect for urban living or as a sophisticated guest house.",
  },
  // GreenBox Homes Latvia models
  {
    id: "m16",
    name: "GreenBox Container",
    slug: "greenbox-container",
    manufacturerId: "6",
    size_sqm: 30,
    bedrooms: 1,
    bathrooms: 1,
    price_range: "€38,000 - €48,000",
    category: "Container Home",
    style_tags: ["Industrial", "Modern", "Container"],
    features: ["Shipping container base", "Modern conversion", "Insulated", "Stackable design", "Portable"],
    images: [
      "https://i.pinimg.com/736x/b1/bc/61/b1bc61af6e5e04b6698440e8a69fc964.jpg",
      "https://i.pinimg.com/1200x/43/25/34/432534d284c5c02f45a13049f17c11e5.jpg",
    ],
    description: "Innovative container home conversion with modern amenities. Sustainable and portable, perfect for alternative living.",
  },
  {
    id: "m17",
    name: "GreenBox Modular",
    slug: "greenbox-modular",
    manufacturerId: "6",
    size_sqm: 72,
    bedrooms: 2,
    bathrooms: 2,
    price_range: "€78,000 - €95,000",
    category: "Modular",
    style_tags: ["Modern", "Contemporary", "Sustainable"],
    features: ["Modular system", "Quick assembly", "Sustainable materials", "Modern design", "Expandable"],
    images: [
      "https://i.pinimg.com/1200x/79/94/df/7994df513ac293554df1356be1bfa8ee.jpg",
      "https://i.pinimg.com/1200x/ab/81/2a/ab812a9afae4bd42678eea3d82546951.jpg",
    ],
    description: "Modern modular home system with sustainable construction. Features quick assembly and expandable design options.",
  },
  {
    id: "m18",
    name: "GreenBox Double",
    slug: "greenbox-double",
    manufacturerId: "6",
    size_sqm: 60,
    bedrooms: 2,
    bathrooms: 1,
    price_range: "€65,000 - €78,000",
    category: "Container Home",
    style_tags: ["Industrial", "Modern", "Container"],
    features: ["Double container design", "Spacious layout", "Modern finishes", "Insulated", "Customizable"],
    images: [
      "https://i.pinimg.com/1200x/83/d7/bc/83d7bcd3f75cc1a24f690bef9cdb642e.jpg",
      "https://i.pinimg.com/1200x/e7/b9/51/e7b9514255e66799c7860c073a78dcf8.jpg",
    ],
    description: "Spacious double-container home with modern design. Combines industrial aesthetics with comfortable living spaces.",
  },
]
